build: false

environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"
    
    CONAN_UPLOAD: 1
    CONAN_REFERENCE: "SQLiteCpp/2.0.0"
    CONAN_USERNAME: "sunside"
    CONAN_CHANNEL: "ci"
    CONAN_TOTAL_PAGES: 1
    
    CONAN_ARCHS: "x86_64,x86"
    CONAN_VISUAL_VERSIONS: "12,14"
    CONAN_VISUAL_RUNTIMES: "MD"
    #MINGW_CONFIGURATIONS: "6.2@x86_64@seh@posix, 4.9@x86_64@seh@posix"
    #MINGW_CONFIGURATIONS: "4.9@x86_64@seh@posix, 4.9@x86_64@seh@win32, 4.9@x86@sjlj@posix, 4.9@x86@dwarf2@posix, 4.9@x86@sjlj@win32, 4.9@x86@dwarf2@win32"

    matrix:
        - CONAN_CURRENT_PAGE: 1

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan_package_tools # It install conan too
  - conan user # It creates the conan data directory

test_script:
  - python build.py
